export const seasonPhotos = [
    {
        season: 1,
        photoMain: 'imgs/s-1-main.jpg',
        photos: [
            '/imgs/season-photos/season-1/s-1-01.jpg',
            '/imgs/season-photos/season-1/s-1-02.jpg',
            '/imgs/season-photos/season-1/s-1-03.heic',
            '/imgs/season-photos/season-1/s-1-04.heic',
            '/imgs/season-photos/season-1/s-1-05.heic',
            '/imgs/season-photos/season-1/s-1-06.heic',
            '/imgs/season-photos/season-1/s-1-07.heic',
            '/imgs/season-photos/season-1/s-1-08.jpg',
            '/imgs/season-photos/season-1/s-1-09.jpg',
            '/imgs/season-photos/season-1/s-1-10.jpg',
            '/imgs/season-photos/season-1/s-1-11.jpg',
            '/imgs/season-photos/season-1/s-1-12.jpg',
            '/imgs/season-photos/season-1/s-1-13.jpg',
            '/imgs/season-photos/season-1/s-1-14.jpg',
            '/imgs/season-photos/season-1/s-1-15.jpg',
        ]
    },
    {
        season: 2,
        photoMain: 'imgs/s-2-main.jpg',
        photos: [
            '/imgs/season-photos/season-2/div-h/s-2-01.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-02.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-03.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-04.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-05.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-06.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-07.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-08.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-09.jpg',
            '/imgs/season-photos/season-2/div-h/s-2-10.jpeg',
            '/imgs/season-photos/season-2/div-h/s-2-11.jpeg',
            '/imgs/season-photos/season-2/div-h/s-2-12.jpeg',
            '/imgs/season-photos/season-2/div-e/s-2-13.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-14.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-15.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-16.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-17.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-18.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-19.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-20.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-21.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-22.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-23.jpg',
            '/imgs/season-photos/season-2/div-e/s-2-13.jpg',
        ]
    },
    {
        season: 3,
        photoMain: 'imgs/s-3-main.jpg',
        photos: [
            '/imgs/season-photos/season-3/div-h/s-3-01.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-02.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-03.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-04.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-05.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-06.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-07.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-08.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-09.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-10.jpg',
            '/imgs/season-photos/season-3/div-h/s-3-11.heic',
            '/imgs/season-photos/season-3/div-e/s-3-12.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-13.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-14.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-15.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-16.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-17.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-18.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-19.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-20.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-21.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-22.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-23.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-24.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-25.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-26.jpg',
            '/imgs/season-photos/season-3/div-e/s-3-27.jpeg',
        ]
    },
]